spring:
  application:
    name: "server-discovery"
  profiles:
    active: "${SCM_ENV:local}"
  cloud:
    config:
      enabled: false

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "info,health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
