version: "3.9"

services:

  server-discovery:
    container_name: server-discovery
    image: apedraza/server-discovery
    ports:
      - "8761:8761"
    networks:
      scm-network:
        aliases:
          - "server-discovery"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    restart: always

  server-zipkin:
    container_name: server-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      scm-network:
        aliases:
          - "server-zipkin"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9411 || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    restart: always
    depends_on:
      server-discovery:
        condition: service_healthy

  server-configuration:
    container_name: server-configuration
    image: apedraza/server-configuration
    ports:
      - "8888:8888"
    networks:
      scm-network:
        aliases:
          - "server-configuration"
    volumes:
      - ${SCM_CONFIG_REPO_LOCAL}:${SCM_CONFIG_REPO_CONTAINER}:ro
    environment:
      - spring.profiles.active=native
      - eureka.client.service-url.defaultZone=${SCM_SERVER_DISCOVERY}
      - spring.cloud.config.server.git.uri=file://${SCM_CONFIG_REPO_CONTAINER}
      - SCM_ZIPKIN_BASEURL=${SCM_ZIPKIN_BASEURL}
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    restart: always
    depends_on:
      server-discovery:
        condition: service_healthy
      server-zipkin:
        condition: service_healthy

  api-gateway:
    container_name: api-gateway
    image: apedraza/api-gateway
    ports:
      - "8765:8765"
    networks:
      scm-network:
        aliases:
          - "api-gateway"
    environment:
      - spring.profiles.active=${SCM_PROFILE}
      - eureka.client.service-url.defaultZone=${SCM_SERVER_DISCOVERY}
      - spring.config.import=configserver:${SCM_SERVER_CONFIGURATION}
      - spring.zipkin.baseUrl=${SCM_ZIPKIN_BASEURL}
    healthcheck:
      test: "curl --fail --silent localhost:8765/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    restart: always
    depends_on:
      server-discovery:
        condition: service_healthy
      server-configuration:
        condition: service_healthy
      server-zipkin:
        condition: service_healthy

  service-file:
    image: apedraza/service-file
    networks:
      scm-network:
        aliases:
          - "service-file"
    environment:
      - SPRING_PROFILES_ACTIVE=${SCM_PROFILE}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${SCM_SERVER_DISCOVERY}
      - SPRING_CONFIG_IMPORT=configserver:${SCM_SERVER_CONFIGURATION}
      - SPRING_ZIPKIN_BASEURL=${SCM_ZIPKIN_BASEURL}
    restart: always
    depends_on:
      server-discovery:
        condition: service_healthy
      server-configuration:
        condition: service_healthy
      server-zipkin:
        condition: service_healthy

  service-folder:
    image: apedraza/service-folder
    networks:
      scm-network:
        aliases:
          - "service-folder"
    environment:
      - SPRING_PROFILES_ACTIVE=${SCM_PROFILE}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${SCM_SERVER_DISCOVERY}
      - SPRING_CONFIG_IMPORT=configserver:${SCM_SERVER_CONFIGURATION}
      - SPRING_ZIPKIN_BASEURL=${SCM_ZIPKIN_BASEURL}
    restart: always
    depends_on:
      server-discovery:
        condition: service_healthy
      server-configuration:
        condition: service_healthy
      server-zipkin:
        condition: service_healthy

networks:
  scm-network:
    driver: bridge
