spring:
  application:
    name: "api-gateway"
  profiles:
    active: "${SCM_ENV:local}"
  config:
    import: "configserver:"
  cloud:
    config:
      profile: ${spring.profiles.active}
      fail-fast: true
  main:
    web-application-type: reactive
