spring:
  application:
    name: "api-gateway"
  profiles:
    active: "local"
  config:
    import: "configserver:${SCM_SERVER_CONFIGURATION:http://localhost:8888}"
  cloud:
    config:
      profile: ${spring.profiles.active}
