spring:
  application:
    name: "service-folder"
  profiles:
    active: "${SCM_ENV:local}"
  config:
    import: "optional:configserver:"
  cloud:
    config:
      profile: ${spring.profiles.active}

---

service-folder:
  allowTrailingSlash: true
