spring:
  application:
    name: "service-folder"
  profiles:
    active: "local"
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: ${spring.profiles.active}

---

service-folder:
  allowTrailingSlash: true
