spring:
  application:
    name: "server-configuration"
  profiles:
    active: "${SCM_ENV:local}"
  cloud:
    config:
      server:
        git:
          uri: ${SCM_SERVER_CONFIG_REPO:git@server-configuration:pedrazamiguez/config-repo.git}
          force-pull: true
          default-label: "main"
          cloneOnStart: true
          search-paths:
            - "shared"
            - "{application}"

server:
  port: 8888

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${SCM_SERVER_DISCOVERY:http://localhost:8761/eureka}
