spring:
  application:
    name: "server-configuration"
  cloud:
    config:
      server:
        git:
          uri: "git@server-configuration:pedrazamiguez/config-repo.git"
          forcePull: true
          defaultLabel: "main"
          cloneOnStart: true
          searchPaths:
            - "shared"
            - "{application}"

server:
  port: 8888

---

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
