spring:
  application:
    name: "service-file"
  profiles:
    active: "local"
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: ${spring.profiles.active}

---

service-file:
  types: "txt,bmp"
  maxFileSize: "1g"
