spring:
  application:
    name: "service-file"
  profiles:
    active: "${SCM_ENV:local}"
  config:
    import: "optional:configserver:"
  cloud:
    config:
      profile: ${spring.profiles.active}
      fail-fast: true

---

service-file:
  types: "txt,bmp"
  maxFileSize: "1g"
